-- MedflowX Hospital Management System Database Schema
-- Compatible with PostgreSQL / Supabase

-- Enable UUID extension for auth integration
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================================
-- 1. ENUM TYPES
-- =========================================================================

CREATE TYPE gender_type AS ENUM ('Male', 'Female', 'Other');

CREATE TYPE visit_status_type AS ENUM (
    'Created',
    'Waiting',
    'In Progress',
    'Prescribed',
    'Sent to Pharmacy',
    'Dispensed',
    'Closed',
    'Cancelled'
);

CREATE TYPE stock_transaction_type AS ENUM ('Purchase', 'Sale', 'Adjustment');

CREATE TYPE payment_mode_enum AS ENUM ('Cash', 'UPI', 'Card');

CREATE TYPE payment_status_enum AS ENUM ('Pending', 'Paid', 'Refund');

CREATE TYPE appointment_status_type AS ENUM ('Booked', 'Completed', 'Cancelled');

-- =========================================================================
-- 2. SEQUENCES & AUTO-GENERATION FUNCTIONS
-- =========================================================================

CREATE SEQUENCE IF NOT EXISTS patient_code_seq START WITH 1;
CREATE SEQUENCE IF NOT EXISTS visit_number_seq START WITH 1;
CREATE SEQUENCE IF NOT EXISTS invoice_number_seq START WITH 1;

-- Patient Code Generator (Format: MED-YYYY-000001)
CREATE OR REPLACE FUNCTION generate_patient_code() 
RETURNS VARCHAR AS $$
BEGIN
  RETURN 'MED-' || TO_CHAR(CURRENT_DATE, 'YYYY') || '-' || LPAD(NEXTVAL('patient_code_seq')::TEXT, 6, '0');
END;
$$ LANGUAGE plpgsql;

-- Visit Number Generator (Format: VIS-YYYYMMDD-00001)
CREATE OR REPLACE FUNCTION generate_visit_number() 
RETURNS VARCHAR AS $$
BEGIN
  RETURN 'VIS-' || TO_CHAR(CURRENT_DATE, 'YYYYMMDD') || '-' || LPAD(NEXTVAL('visit_number_seq')::TEXT, 5, '0');
END;
$$ LANGUAGE plpgsql;

-- Invoice Number Generator (Format: INV-YYYYMMDD-00001)
CREATE OR REPLACE FUNCTION generate_invoice_number() 
RETURNS VARCHAR AS $$
BEGIN
  RETURN 'INV-' || TO_CHAR(CURRENT_DATE, 'YYYYMMDD') || '-' || LPAD(NEXTVAL('invoice_number_seq')::TEXT, 5, '0');
END;
$$ LANGUAGE plpgsql;

-- Automated updated_at trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================================
-- 3. TABLES (In dependency order)
-- =========================================================================

-- 1. roles
CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) UNIQUE NOT NULL,
    description TEXT
);

-- 2. profiles (Extends Supabase auth.users)
CREATE TABLE profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES roles(id),
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) UNIQUE,
    phone VARCHAR(20) UNIQUE,
    is_active BOOLEAN DEFAULT TRUE,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 3. departments
CREATE TABLE departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(100) UNIQUE NOT NULL
);

-- 4. doctors
CREATE TABLE doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID UNIQUE REFERENCES profiles(id) ON DELETE CASCADE,
    department_id INTEGER REFERENCES departments(id) ON DELETE SET NULL,
    qualification VARCHAR(150),
    consultation_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 5. patients
CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_code VARCHAR(30) UNIQUE NOT NULL DEFAULT generate_patient_code(),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),
    gender gender_type NOT NULL,
    dob DATE,
    age INTEGER,
    blood_group VARCHAR(10),
    phone VARCHAR(20),
    email VARCHAR(150),
    emergency_contact VARCHAR(20),
    occupation VARCHAR(100),
    allergies TEXT,
    medical_history TEXT,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 6. patient_addresses
CREATE TABLE patient_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
    address_line TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    district VARCHAR(100),
    state VARCHAR(100) NOT NULL,
    country VARCHAR(100) DEFAULT 'India',
    pincode VARCHAR(10) NOT NULL,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 7. visits
CREATE TABLE visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_number VARCHAR(30) UNIQUE NOT NULL DEFAULT generate_visit_number(),
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
    doctor_id BIGINT REFERENCES doctors(id) ON DELETE RESTRICT,
    visit_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    token_no INTEGER NOT NULL,
    chief_complaint TEXT,
    status visit_status_type DEFAULT 'Created',
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 8. visit_status_history
CREATE TABLE visit_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id BIGINT REFERENCES visits(id) ON DELETE CASCADE,
    status visit_status_type NOT NULL,
    remarks TEXT,
    changed_by UUID REFERENCES profiles(id),
    changed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 9. diagnoses
CREATE TABLE diagnoses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id BIGINT REFERENCES visits(id) ON DELETE CASCADE,
    symptoms TEXT,
    clinical_findings TEXT,
    diagnosis TEXT NOT NULL,
    doctor_notes TEXT,
    follow_up_advice TEXT,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 10. prescriptions
CREATE TABLE prescriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id BIGINT REFERENCES visits(id) ON DELETE CASCADE,
    doctor_id BIGINT REFERENCES doctors(id) ON DELETE RESTRICT,
    advice TEXT,
    follow_up_date DATE,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 11. medicine_categories
CREATE TABLE medicine_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) UNIQUE NOT NULL,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 12. medicines
CREATE TABLE medicines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER REFERENCES medicine_categories(id) ON DELETE SET NULL,
    medicine_name VARCHAR(150) UNIQUE NOT NULL,
    generic_name VARCHAR(150),
    strength VARCHAR(50),
    manufacturer VARCHAR(100),
    unit VARCHAR(20),
    reorder_level INTEGER DEFAULT 10,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 13. medicine_batches
CREATE TABLE medicine_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id BIGINT REFERENCES medicines(id) ON DELETE CASCADE,
    batch_no VARCHAR(100) NOT NULL,
    expiry_date DATE NOT NULL,
    purchase_price DECIMAL(10,2) NOT NULL,
    selling_price DECIMAL(10,2) NOT NULL,
    available_quantity INTEGER NOT NULL DEFAULT 0,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id),
    UNIQUE (medicine_id, batch_no)
);

-- 14. prescription_items
CREATE TABLE prescription_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id BIGINT REFERENCES prescriptions(id) ON DELETE CASCADE,
    medicine_id BIGINT REFERENCES medicines(id) ON DELETE RESTRICT,
    dosage VARCHAR(100) NOT NULL,
    frequency VARCHAR(100) NOT NULL,
    duration VARCHAR(100) NOT NULL,
    quantity INTEGER NOT NULL,
    instructions TEXT,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 15. medicine_stock_history
CREATE TABLE medicine_stock_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id BIGINT REFERENCES medicines(id) ON DELETE CASCADE,
    batch_id BIGINT REFERENCES medicine_batches(id) ON DELETE SET NULL,
    transaction_type stock_transaction_type NOT NULL,
    quantity INTEGER NOT NULL,
    balance INTEGER NOT NULL,
    remarks TEXT,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES profiles(id)
);

-- 16. invoices
CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(30) UNIQUE NOT NULL DEFAULT generate_invoice_number(),
    visit_id BIGINT REFERENCES visits(id) ON DELETE SET NULL,
    patient_id BIGINT REFERENCES patients(id) ON DELETE SET NULL,
    total_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    discount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    tax DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    final_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    paid_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(50) NOT NULL DEFAULT 'Unpaid',
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 17. invoice_items
CREATE TABLE invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT REFERENCES invoices(id) ON DELETE CASCADE,
    item_type VARCHAR(50) NOT NULL,
    reference_id BIGINT,
    description TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price DECIMAL(10,2) NOT NULL,
    total_price DECIMAL(10,2) NOT NULL,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 18. payments
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT REFERENCES invoices(id) ON DELETE CASCADE,
    amount DECIMAL(10,2) NOT NULL,
    payment_mode payment_mode_enum NOT NULL,
    payment_status payment_status_enum NOT NULL DEFAULT 'Pending',
    transaction_reference VARCHAR(100),
    paid_at TIMESTAMPTZ,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 19. pharmacy_sales
CREATE TABLE pharmacy_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id BIGINT REFERENCES visits(id) ON DELETE SET NULL,
    patient_id BIGINT REFERENCES patients(id) ON DELETE SET NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    discount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    final_amount DECIMAL(10,2) NOT NULL,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 20. pharmacy_sale_items
CREATE TABLE pharmacy_sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT REFERENCES pharmacy_sales(id) ON DELETE CASCADE,
    medicine_id BIGINT REFERENCES medicines(id) ON DELETE RESTRICT,
    batch_id BIGINT REFERENCES medicine_batches(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    total DECIMAL(10,2) NOT NULL,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 21. appointments
CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
    doctor_id BIGINT REFERENCES doctors(id) ON DELETE RESTRICT,
    appointment_date TIMESTAMPTZ NOT NULL,
    status appointment_status_type DEFAULT 'Booked',
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 22. audit_logs
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    action VARCHAR(255) NOT NULL,
    table_name VARCHAR(100) NOT NULL,
    record_id VARCHAR(100),
    old_values JSONB,
    new_values JSONB,
    ip_address VARCHAR(45),
    device TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 23. patient_documents
CREATE TABLE patient_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
    visit_id BIGINT REFERENCES visits(id) ON DELETE SET NULL,
    file_url TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_type VARCHAR(50),
    file_size INTEGER,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 24. notifications
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    receiver_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    is_read BOOLEAN DEFAULT FALSE,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- 25. settings
CREATE TABLE settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_name VARCHAR(150) NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(150),
    logo_url TEXT,
    gst_number VARCHAR(50),
    address TEXT,
    currency VARCHAR(10) DEFAULT 'INR',
    consultation_fee DECIMAL(10,2) DEFAULT 0.00,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by UUID REFERENCES profiles(id),
    updated_by UUID REFERENCES profiles(id)
);

-- =========================================================================
-- 4. TRIGGERS FOR AUTOMATED updated_at
-- =========================================================================

CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_doctors_updated_at BEFORE UPDATE ON doctors FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_patients_updated_at BEFORE UPDATE ON patients FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_patient_addresses_updated_at BEFORE UPDATE ON patient_addresses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_visits_updated_at BEFORE UPDATE ON visits FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_diagnoses_updated_at BEFORE UPDATE ON diagnoses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_prescriptions_updated_at BEFORE UPDATE ON prescriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_medicine_categories_updated_at BEFORE UPDATE ON medicine_categories FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_medicines_updated_at BEFORE UPDATE ON medicines FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_medicine_batches_updated_at BEFORE UPDATE ON medicine_batches FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_prescription_items_updated_at BEFORE UPDATE ON prescription_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_invoices_updated_at BEFORE UPDATE ON invoices FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_invoice_items_updated_at BEFORE UPDATE ON invoice_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_payments_updated_at BEFORE UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_pharmacy_sales_updated_at BEFORE UPDATE ON pharmacy_sales FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_pharmacy_sale_items_updated_at BEFORE UPDATE ON pharmacy_sale_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_appointments_updated_at BEFORE UPDATE ON appointments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_patient_documents_updated_at BEFORE UPDATE ON patient_documents FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_notifications_updated_at BEFORE UPDATE ON notifications FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_settings_updated_at BEFORE UPDATE ON settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =========================================================================
-- 5. MATERIALIZED VIEWS FOR DASHBOARD PERFORMANCE
-- =========================================================================

-- Daily Revenue View
CREATE MATERIALIZED VIEW daily_revenue AS
SELECT 
    DATE(paid_at) AS revenue_date,
    SUM(amount) AS total_revenue,
    COUNT(id) AS transaction_count
FROM payments
WHERE payment_status = 'Paid' AND deleted_at IS NULL
GROUP BY DATE(paid_at)
WITH DATA;

-- Monthly Revenue View
CREATE MATERIALIZED VIEW monthly_revenue AS
SELECT 
    DATE_TRUNC('month', paid_at) AS revenue_month,
    SUM(amount) AS total_revenue,
    COUNT(id) AS transaction_count
FROM payments
WHERE payment_status = 'Paid' AND deleted_at IS NULL
GROUP BY DATE_TRUNC('month', paid_at)
WITH DATA;

-- Doctor Statistics View
CREATE MATERIALIZED VIEW doctor_statistics AS
SELECT 
    d.id AS doctor_id,
    p.full_name AS doctor_name,
    dept.department_name,
    COUNT(v.id) AS total_visits,
    COUNT(CASE WHEN v.status = 'Closed' THEN 1 END) as completed_visits,
    COALESCE(SUM(inv.final_amount), 0) AS total_revenue_generated
FROM doctors d
JOIN profiles p ON d.user_id = p.id
LEFT JOIN departments dept ON d.department_id = dept.id
LEFT JOIN visits v ON d.id = v.doctor_id AND v.deleted_at IS NULL
LEFT JOIN invoices inv ON v.id = inv.visit_id AND inv.status = 'Paid' AND inv.deleted_at IS NULL
WHERE d.deleted_at IS NULL
GROUP BY d.id, p.full_name, dept.department_name
WITH DATA;

-- Create Indexes on Materialized Views for efficient lookup
CREATE UNIQUE INDEX idx_daily_revenue_date ON daily_revenue (revenue_date);
CREATE UNIQUE INDEX idx_monthly_revenue_month ON monthly_revenue (revenue_month);
CREATE UNIQUE INDEX idx_doctor_stats_id ON doctor_statistics (doctor_id);

-- =========================================================================
-- 6. SEED DATA
-- =========================================================================

-- Insert roles
INSERT INTO roles (id, role_name, description) VALUES
(1, 'Admin', 'Hospital Administrator with full system access'),
(2, 'Reception', 'Receptionist managing patient registration, visits, and billing'),
(3, 'Doctor', 'Medical practitioner managing diagnoses and prescriptions'),
(4, 'Pharmacy', 'Pharmacist managing medicine inventory and sales')
ON CONFLICT (id) DO UPDATE SET 
  role_name = EXCLUDED.role_name, 
  description = EXCLUDED.description;

-- Insert departments
INSERT INTO departments (id, department_name) VALUES
(1, 'General Medicine'),
(2, 'ENT'),
(3, 'Dental'),
(4, 'Cardiology')
ON CONFLICT (id) DO UPDATE SET 
  department_name = EXCLUDED.department_name;

-- Fix identity sequences after manual ID seeding
SELECT setval(pg_get_serial_sequence('roles', 'id'), COALESCE(MAX(id), 1)) FROM roles;
SELECT setval(pg_get_serial_sequence('departments', 'id'), COALESCE(MAX(id), 1)) FROM departments;
